version: '3'
services: 
  nginx:
    build: 
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
  servicio1:
    build: 
      context: ./Servidor1
      dockerfile: Dockerfile
    container_name: servidor1
    ports:
      - "5001:5000"
  servicio2:
    build: 
      context: ./Servidor2
      dockerfile: Dockerfile
    container_name: servidor2
    ports:
      - "5002:5000"
  servicio3:
    build: 
      context: ./Servidor3
      dockerfile: Dockerfile
    container_name: servidor3
    ports:
      - "5003:5000"

  locust:
    image: locustio/locust:latest
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - C:\Users\APP DISTRIBUIDAS\Desktop\das:/mnt/locust
    command: ["-f","/mnt/locust/locustfile.py"]